spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/tweetapp
    password: password
  application:
    name: TweetAppService
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5Dialect
      
logging:
  file:
    path: './config/logs'
    name: ${logging.file.path}/my-app.log
  level:
    org.springframework.web: ERROR
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
client:
  url: http://localhost:4200